//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 12:08:09 PM CET 
//


package com.resanet.camel_su.oxm.reservationWeb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idReservation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateReservation" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="produit" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="codeProduit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codeTarifaire" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="quantite" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idReservation",
    "dateReservation",
    "produit"
})
@XmlRootElement(name = "reservation")
public class ReservationWeb {

    @XmlElement(required = true)
    protected String idReservation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateReservation;
    @XmlElement(required = true)
    protected List<ReservationWeb.Produit> produit;

    /**
     * Gets the value of the idReservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdReservation() {
        return idReservation;
    }

    /**
     * Sets the value of the idReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdReservation(String value) {
        this.idReservation = value;
    }

    /**
     * Gets the value of the dateReservation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateReservation() {
        return dateReservation;
    }

    /**
     * Sets the value of the dateReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReservation(XMLGregorianCalendar value) {
        this.dateReservation = value;
    }

    /**
     * Gets the value of the produit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the produit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationWeb.Produit }
     * 
     * 
     */
    public List<ReservationWeb.Produit> getProduit() {
        if (produit == null) {
            produit = new ArrayList<ReservationWeb.Produit>();
        }
        return this.produit;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="codeProduit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codeTarifaire" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="quantite" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codeProduit",
        "codeTarifaire",
        "quantite"
    })
    public static class Produit {

        @XmlElement(required = true)
        protected String codeProduit;
        @XmlElement(required = true)
        protected String codeTarifaire;
        protected int quantite;

        /**
         * Gets the value of the codeProduit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeProduit() {
            return codeProduit;
        }

        /**
         * Sets the value of the codeProduit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeProduit(String value) {
            this.codeProduit = value;
        }

        /**
         * Gets the value of the codeTarifaire property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeTarifaire() {
            return codeTarifaire;
        }

        /**
         * Sets the value of the codeTarifaire property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeTarifaire(String value) {
            this.codeTarifaire = value;
        }

        /**
         * Gets the value of the quantite property.
         * 
         */
        public int getQuantite() {
            return quantite;
        }

        /**
         * Sets the value of the quantite property.
         * 
         */
        public void setQuantite(int value) {
            this.quantite = value;
        }

    }

}
