
package com.resanet.common;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Dec 23 19:00:40 CET 2009
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "trouverHotelFault", targetNamespace = "http://www.resanet.partenaires.com/hotel")
public class RechercherHotelFault extends Exception {
    public static final long serialVersionUID = 20091223190040L;
    
    private java.lang.String rechercherHotelFault;

    public RechercherHotelFault() {
        super();
    }
    
    public RechercherHotelFault(String message) {
        super(message);
    }
    
    public RechercherHotelFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RechercherHotelFault(String message, java.lang.String rechercherHotelFault) {
        super(message);
        this.rechercherHotelFault = rechercherHotelFault;
    }

    public RechercherHotelFault(String message, java.lang.String rechercherHotelFault, Throwable cause) {
        super(message, cause);
        this.rechercherHotelFault = rechercherHotelFault;
    }

    public java.lang.String getFaultInfo() {
        return this.rechercherHotelFault;
    }
}
