//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 12:27:40 PM CET 
//


package com.resanet.camel_su.oxm.reservationResa;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.resanet.camel_su.oxm.ReservationResa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.resanet.camel_su.oxm.ReservationResa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReservationResa }
     * 
     */
    public ReservationResa createReservation() {
        return new ReservationResa();
    }

    /**
     * Create an instance of {@link ReservationResa.AttributsReservation }
     * 
     */
    public ReservationResa.AttributsReservation createReservationAttributsReservation() {
        return new ReservationResa.AttributsReservation();
    }

    /**
     * Create an instance of {@link ReservationResa.Produits }
     * 
     */
    public ReservationResa.Produits createReservationProduits() {
        return new ReservationResa.Produits();
    }

}
