//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 12:27:40 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://esb.resanet.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.resanet.camel_su.oxm.reservationResa;
