package com.resanet.informations;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-12-19T14:32:23.564+01:00
 * Generated source version: 2.3.2
 * 
 */
 
@WebService(targetNamespace = "http://www.resanet.com/informations", name = "detourPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DetourPortType {

    @Oneway
    @WebMethod
    public void detour(
        @WebParam(partName = "parameters", name = "detour", targetNamespace = "http://www.resanet.com/informations")
        boolean parameters
    );
}
