//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.03 at 08:00:19 PM CET 
//

package com.resanet.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;resa&quot; maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name=&quot;produit&quot;&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *                         &lt;maxLength value=&quot;3&quot;/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name=&quot;date&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot;/&gt;
 *                   &lt;element name=&quot;quantite&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", namespace = "http://resa.resanet.com", propOrder = { "resa" })
@XmlRootElement(name = "reservation", namespace = "http://resa.resanet.com")
public class Reservation {

	@XmlElement(required = true, namespace = "http://resa.resanet.com")
	protected List<Reservation.Resa> resa;

	/**
	 * Gets the value of the resa property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the resa property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getResa().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Reservation.Resa }
	 * 
	 * 
	 */
	public List<Reservation.Resa> getResa() {
		if (resa == null) {
			resa = new ArrayList<Reservation.Resa>();
		}
		return this.resa;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name=&quot;produit&quot;&gt;
	 *           &lt;simpleType&gt;
	 *             &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
	 *               &lt;maxLength value=&quot;3&quot;/&gt;
	 *             &lt;/restriction&gt;
	 *           &lt;/simpleType&gt;
	 *         &lt;/element&gt;
	 *         &lt;element name=&quot;date&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot;/&gt;
	 *         &lt;element name=&quot;quantite&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", namespace = "http://resa.resanet.com", propOrder = { "produit", "date", "quantite" })
	public static class Resa {

		@XmlElement(required = true, namespace = "http://resa.resanet.com")
		protected String produit;
		@XmlElement(required = true, namespace = "http://resa.resanet.com")
		@XmlSchemaType(name = "date", namespace = "http://resa.resanet.com")
		protected XMLGregorianCalendar date;
		@XmlElement(required = true, namespace = "http://resa.resanet.com")
		protected int quantite;

		/**
		 * Gets the value of the produit property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProduit() {
			return produit;
		}

		/**
		 * Sets the value of the produit property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setProduit(String value) {
			this.produit = value;
		}

		/**
		 * Gets the value of the date property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDate() {
			return date;
		}

		/**
		 * Sets the value of the date property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDate(XMLGregorianCalendar value) {
			this.date = value;
		}

		/**
		 * Gets the value of the quantite property.
		 * 
		 */
		public int getQuantite() {
			return quantite;
		}

		/**
		 * Sets the value of the quantite property.
		 * 
		 */
		public void setQuantite(int value) {
			this.quantite = value;
		}

	}

	public String toCSV() {
		StringBuilder sb = new StringBuilder("produit;date;quantite");
		sb.append(System.getProperty("line.separator"));
		for (Resa r : resa) {
			sb.append(r.getProduit());
			sb.append(";");
			sb.append(r.getDate());
			sb.append(";");
			sb.append(r.getQuantite());
			sb.append(System.getProperty("line.separator"));
		}
		return sb.toString();
	}

}
