
/*
 * 
 */

package com.resanet.informations;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-12-19T14:32:23.786+01:00
 * Generated source version: 2.3.2
 * 
 */


@WebServiceClient(name = "detourService", 
                  wsdlLocation = "file:/C:/workspace_esb/tp12/src/main/resources/wsdl/controle.wsdl",
                  targetNamespace = "http://www.resanet.com/informations") 
public class DetourService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.resanet.com/informations", "detourService");
    public final static QName DetourServicePort = new QName("http://www.resanet.com/informations", "detourServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace_esb/tp12/src/main/resources/wsdl/controle.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/workspace_esb/tp12/src/main/resources/wsdl/controle.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DetourService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DetourService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetourService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns DetourPortType
     */
    @WebEndpoint(name = "detourServicePort")
    public DetourPortType getDetourServicePort() {
        return super.getPort(DetourServicePort, DetourPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetourPortType
     */
    @WebEndpoint(name = "detourServicePort")
    public DetourPortType getDetourServicePort(WebServiceFeature... features) {
        return super.getPort(DetourServicePort, DetourPortType.class, features);
    }

}
